[project]
name = "candiamazing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ErikOsinga", email = "erikosinga876@hotmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "astropy>=7.2.0",
    "numpy>=2.3.5",
]

[project.scripts]
candiamazing = "candiamazing:main"
calcrm = "candiamazing.cli:main"

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[project.optional-dependencies]
dev = ["ruff"]

[tool.ruff]
# Apply to both src and tests by default
src = ["src", "tests"]

[tool.ruff.lint]
# Can expand this as far as user wants
select = [
  "E",   # pycodestyle (PEP8) errors
  "F",   # pyflakes
  "I",   # isort-like import sorting
  "B",   # bugbear (common bugs)
  "UP",  # pyupgrade (modern Python idioms)
]
ignore = [
  "E501",  # line length
]


